# Generated by Django 6.0.4 on 2026-05-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('youth', 'Youth')], db_index=True, default='women', max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('height', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='actors/profile/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modelprofile',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('youth', 'Youth')], db_index=True, default='women', max_length=10),
        ),
        migrations.CreateModel(
            name='ActorPortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actors/portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='core.actorprofile')),
            ],
        ),
    ]
