# Generated by Django 6.0.4 on 2026-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actorprofile_modelprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('model', 'Model'), ('actor', 'Actor')], default='model', max_length=10),
        ),
        migrations.AlterField(
            model_name='actorportfolioimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actorprofile',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='images',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
