# Generated by Django 6.0.4 on 2026-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
    ]
